### ISSUE TITLE
Endless Loop

### ISSUE THREAD

**Issue by yashkolambekar** [YugBhanushali/ZipURL#1]
Hey Yug,

There's a flaw in the authenticator which takes the source urls from the user, it should not take it's own url's or atleast the url it takes should not be equal to the one it produces. To put it in understandable words **source url != zipped url**

I just created the url [https://zipurl.tech/loop](url) and it just keeps redirecting to itself. Just add a condition which prevents the same

![ZipURL](https://github.com/YugBhanushali/ZipURL/assets/41070233/d9190974-5d71-4ce8-9069-93e2e4c5d7b4)

**Comment by YugBhanushali** [comment]
Thanks for reporting this bug. I have fixed this bug.
